### ISSUE TITLE
大佬 部署完之后发现没有评论区 搜索search.xml文件404

### ISSUE THREAD

**Issue by cj919837775** [sqlsec/Django-Hexo-Matery#3]

**Comment by sqlsec** [comment]
这个 Django 的我还没有写评论功能，理论上来说有后端的话 就不需要 search.xml文件了，这种评论方式并不友好

**Comment by wxy2077** [comment]
我这个 #2 自己手动加了评论，只支持github登录，但是我感觉使用体验不好(凭感觉写的评论功能,还不完善)
